project:
  type: website

website:
  title: "PauloVillarroel.com"
  site-url: "https://www.paulovillarroel.com/"
  page-navigation: true
  repo-url: https://github.com/paulovillarroel/mi_blog
  repo-actions: [issue]
  google-analytics: "G-RNWVZS7ZL8"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/paulovillarroel
      - icon: twitter
        href: https://twitter.com/Chazkon
      - icon: linkedin
        href: https://www.linkedin.com/in/paulovillarroeltapia/
format:
  html:
    smooth-scroll: true
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    link-external-newwindow: true

editor: visual

comments:
  giscus:
    repo: paulovillarroel/mi_blog